ConsultationAppointmentClient/Controllers/AppointmentController.cs
using ConsultationAppointmentClient.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.DotNet.Scaffolding.Shared.ProjectModel;

namespace ConsultationAppointmentClient.Controllers
{
    public class AppointmentController : Controller
    {
        private readonly APIGateway apiGateway;

        //Dependency injection
        public AppointmentController(APIGateway ApiGateway)
        {
            this.apiGateway = ApiGateway;
        }
        public IActionResult Index(string curre, string rolename)
        {

            string? role = TempData["Role"] as string;
            string? userrole = HttpContext.Session.GetString("Role");


            if (userrole=="Receptionist" || userrole == "Admin")
            {
                List<Appointment> appointments;
                //API GET Will come
                appointments = apiGateway.ListAppointments();
                return View(appointments);
            }
            else
            {
               return RedirectToAction("Login","Home");
            }
        }

        //create
        [HttpGet]
        public IActionResult Create()
        {
            string? role = TempData["Role"] as string;
            string? userrole = HttpContext.Session.GetString("Role");


            if (userrole == "Receptionist" || userrole == "Admin")
            {
                Appointment appointment = new Appointment();
                return View(appointment);
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }
            [HttpPost]
        public IActionResult Create(Appointment appointment) 
        {
            apiGateway.CreateAppointment(appointment);
            //do the API create and send the control to Index Action
            return RedirectToAction("Success","Home");

        }

        public IActionResult Details(int appointmentId)
        {
            string? role = TempData["Role"] as string;
            string? userrole = HttpContext.Session.GetString("Role");


            if (userrole == "Receptionist" || userrole == "Admin")
            {
                Appointment appointment = new Appointment();
                // fetch the appointment from the API and show the appointment details in the Details View
                appointment = apiGateway.GetAppointment(appointmentId);
                return View(appointment);
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }
        //edit method
        [HttpGet]
        public IActionResult Edit(int appointmentId)
        {
            string? role = TempData["Role"] as string;
            string? userrole = HttpContext.Session.GetString("Role");


            if (userrole == "Receptionist" || userrole == "Admin")
            {
                Appointment appointment;
                //fetch the appointment from the API and show the appointment details in the edit view
                appointment = apiGateway.GetAppointment(appointmentId);
                return View(appointment);
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }

        }
        [HttpPost]
        public IActionResult Edit(Appointment appointment)
        {
            //do the API edit action and send the control to the Index Action
            apiGateway.UpdateAppointment(appointment);
            return RedirectToAction("index");
        }

        //delete method
        [HttpGet]
        public IActionResult Delete(int AppointmentId)
        {
            string? role = TempData["Role"] as string;
            string? userrole = HttpContext.Session.GetString("Role");


            if (userrole == "Admin")
            {
                Appointment appointment;
                appointment = apiGateway.GetAppointment(AppointmentId);
                return View(appointment);
            }
            else
            {
                return RedirectToAction("Login", "Home");

            }
        }
        [HttpPost]
        public IActionResult Delete(Appointment appointment)
        {
            //do the API delete action and send the control to Index action
            apiGateway.DeleteAppointment(appointment.AppointmentId);
            return RedirectToAction("index");
        }
    }
}

ConsultationAppointmentClient/Controllers/ConsultantController.cs
using ConsultationAppointmentClient.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.DotNet.Scaffolding.Shared.ProjectModel;

namespace ConsultationAppointmentClient.Controllers
{
    public class ConsultantController : Controller
    {
        private readonly ConsultationAPI consultationGateway;


        public ConsultantController(ConsultationAPI ConsultationAPI)
        {
            this.consultationGateway = ConsultationAPI;
        }
        public IActionResult Index()
        {
            List<Consultant> consultants= new List<Consultant>();
            consultants = consultationGateway.ListConsultants();
            return View(consultants);
        }



        //Create consultant
        [HttpGet]
        public IActionResult Create()
        {
            Consultant consultant = new Consultant();
            return View(consultant);
        }

        [HttpPost]
        public IActionResult Create(Consultant consultant)
        {
            consultationGateway.CreateConsultant(consultant);
            return RedirectToAction("index");
        }

        //details
        public IActionResult Details(int consultantId)
        {
            Consultant consultant = new Consultant();
            consultant = consultationGateway.GetConsultant(consultantId);
            return View(consultant);
        }

        //Edit
        [HttpGet]
        public IActionResult Edit(int consultantId)
        {
            Consultant consultant = new Consultant();
            consultant = consultationGateway.GetConsultant(consultantId);
            return View(consultant);
        }

        [HttpPost]
        public IActionResult Edit(Consultant consultant)
        {
            consultationGateway.UpdateConsultant(consultant);
            return RedirectToAction("index");
        }

        //Delete
        [HttpGet]
        public IActionResult Delete(int consultantId)
        {
            Consultant consultant = new Consultant();
            consultant = consultationGateway.GetConsultant(consultantId);
            return View(consultant);
        }

        [HttpPost]
        public IActionResult Delete(Consultant consultant)
        {
            consultationGateway.DeleteConsultant(consultant.ConsultantId);
            return RedirectToAction("index");
        }
    }
}

ConsultationAppointmentClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ConsultationAppointmentClient</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ConsultationAppointmentClient.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Consultation Appointment System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav justify-content-center flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark fw-bold" asp-area="" asp-controller="Appointment" asp-action="Create">Create Appointment</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark fw-bold" > | </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark fw-bold" asp-area="" asp-controller="Consultant" asp-action="Index">View Consultants</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container mw-100 mh-100">
        <main role="main" class="pb-3 mw-100 mh-100">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-light">
            &copy; st20284597 - Consultation Appointment System - <a asp-area="" class="text-light" asp-controller="Appointment" asp-action="Index">Home</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>